export type ReportItem = {
  id: string;
  textSnippet: string;
  platform?: string;
  classification?: string;
  rawClassification?: string;
  toxicityScore?: number | null;
  date?: string;
  url?: string;
  classification_status?: string;
  fallback_used?: boolean;
  review_recommended?: boolean;
  review_status?: "unreviewed" | "correct" | "incorrect" | "needs_review" | null;
  corrected_label?: string | null;
  reviewer_note?: string | null;
  reviewed_by?: string | null;
  reviewed_at?: string | null;
  parse_status?: string;
  sheet_status?: string;
  ai_explanation?: string;
};